appVersion: 1.0.0
metadata:
  isMaster: False
  uid: 0
cluster:
  mainTable: none # The largest/most visited table's name
  maxTables: 18   # The capacity for tables
  neighbor: 0     # One of its neighbor's uid
network:
  timeOut: 5
  ip: 0.0.0.0
  port: 7777


