/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package RPC.test;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-05-05")
public class Local implements org.apache.thrift.TBase<Local, Local._Fields>, java.io.Serializable, Cloneable, Comparable<Local> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Local");

  private static final org.apache.thrift.protocol.TField CACHE_FIELD_DESC = new org.apache.thrift.protocol.TField("cache", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField MASTER_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("masterIP", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField MASTER_PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("masterPort", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LocalStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LocalTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<cacheTable> cache; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String masterIP; // required
  public int masterPort; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CACHE((short)1, "cache"),
    MASTER_IP((short)2, "masterIP"),
    MASTER_PORT((short)3, "masterPort");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CACHE
          return CACHE;
        case 2: // MASTER_IP
          return MASTER_IP;
        case 3: // MASTER_PORT
          return MASTER_PORT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MASTERPORT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CACHE, new org.apache.thrift.meta_data.FieldMetaData("cache", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, cacheTable.class))));
    tmpMap.put(_Fields.MASTER_IP, new org.apache.thrift.meta_data.FieldMetaData("masterIP", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MASTER_PORT, new org.apache.thrift.meta_data.FieldMetaData("masterPort", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Local.class, metaDataMap);
  }

  public Local() {
  }

  public Local(
    java.util.List<cacheTable> cache,
    java.lang.String masterIP,
    int masterPort)
  {
    this();
    this.cache = cache;
    this.masterIP = masterIP;
    this.masterPort = masterPort;
    setMasterPortIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Local(Local other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCache()) {
      java.util.List<cacheTable> __this__cache = new java.util.ArrayList<cacheTable>(other.cache.size());
      for (cacheTable other_element : other.cache) {
        __this__cache.add(new cacheTable(other_element));
      }
      this.cache = __this__cache;
    }
    if (other.isSetMasterIP()) {
      this.masterIP = other.masterIP;
    }
    this.masterPort = other.masterPort;
  }

  public Local deepCopy() {
    return new Local(this);
  }

  @Override
  public void clear() {
    this.cache = null;
    this.masterIP = null;
    setMasterPortIsSet(false);
    this.masterPort = 0;
  }

  public int getCacheSize() {
    return (this.cache == null) ? 0 : this.cache.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<cacheTable> getCacheIterator() {
    return (this.cache == null) ? null : this.cache.iterator();
  }

  public void addToCache(cacheTable elem) {
    if (this.cache == null) {
      this.cache = new java.util.ArrayList<cacheTable>();
    }
    this.cache.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<cacheTable> getCache() {
    return this.cache;
  }

  public Local setCache(@org.apache.thrift.annotation.Nullable java.util.List<cacheTable> cache) {
    this.cache = cache;
    return this;
  }

  public void unsetCache() {
    this.cache = null;
  }

  /** Returns true if field cache is set (has been assigned a value) and false otherwise */
  public boolean isSetCache() {
    return this.cache != null;
  }

  public void setCacheIsSet(boolean value) {
    if (!value) {
      this.cache = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMasterIP() {
    return this.masterIP;
  }

  public Local setMasterIP(@org.apache.thrift.annotation.Nullable java.lang.String masterIP) {
    this.masterIP = masterIP;
    return this;
  }

  public void unsetMasterIP() {
    this.masterIP = null;
  }

  /** Returns true if field masterIP is set (has been assigned a value) and false otherwise */
  public boolean isSetMasterIP() {
    return this.masterIP != null;
  }

  public void setMasterIPIsSet(boolean value) {
    if (!value) {
      this.masterIP = null;
    }
  }

  public int getMasterPort() {
    return this.masterPort;
  }

  public Local setMasterPort(int masterPort) {
    this.masterPort = masterPort;
    setMasterPortIsSet(true);
    return this;
  }

  public void unsetMasterPort() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MASTERPORT_ISSET_ID);
  }

  /** Returns true if field masterPort is set (has been assigned a value) and false otherwise */
  public boolean isSetMasterPort() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MASTERPORT_ISSET_ID);
  }

  public void setMasterPortIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MASTERPORT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CACHE:
      if (value == null) {
        unsetCache();
      } else {
        setCache((java.util.List<cacheTable>)value);
      }
      break;

    case MASTER_IP:
      if (value == null) {
        unsetMasterIP();
      } else {
        setMasterIP((java.lang.String)value);
      }
      break;

    case MASTER_PORT:
      if (value == null) {
        unsetMasterPort();
      } else {
        setMasterPort((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CACHE:
      return getCache();

    case MASTER_IP:
      return getMasterIP();

    case MASTER_PORT:
      return getMasterPort();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CACHE:
      return isSetCache();
    case MASTER_IP:
      return isSetMasterIP();
    case MASTER_PORT:
      return isSetMasterPort();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Local)
      return this.equals((Local)that);
    return false;
  }

  public boolean equals(Local that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_cache = true && this.isSetCache();
    boolean that_present_cache = true && that.isSetCache();
    if (this_present_cache || that_present_cache) {
      if (!(this_present_cache && that_present_cache))
        return false;
      if (!this.cache.equals(that.cache))
        return false;
    }

    boolean this_present_masterIP = true && this.isSetMasterIP();
    boolean that_present_masterIP = true && that.isSetMasterIP();
    if (this_present_masterIP || that_present_masterIP) {
      if (!(this_present_masterIP && that_present_masterIP))
        return false;
      if (!this.masterIP.equals(that.masterIP))
        return false;
    }

    boolean this_present_masterPort = true;
    boolean that_present_masterPort = true;
    if (this_present_masterPort || that_present_masterPort) {
      if (!(this_present_masterPort && that_present_masterPort))
        return false;
      if (this.masterPort != that.masterPort)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCache()) ? 131071 : 524287);
    if (isSetCache())
      hashCode = hashCode * 8191 + cache.hashCode();

    hashCode = hashCode * 8191 + ((isSetMasterIP()) ? 131071 : 524287);
    if (isSetMasterIP())
      hashCode = hashCode * 8191 + masterIP.hashCode();

    hashCode = hashCode * 8191 + masterPort;

    return hashCode;
  }

  @Override
  public int compareTo(Local other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetCache(), other.isSetCache());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCache()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cache, other.cache);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMasterIP(), other.isSetMasterIP());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMasterIP()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.masterIP, other.masterIP);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMasterPort(), other.isSetMasterPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMasterPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.masterPort, other.masterPort);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Local(");
    boolean first = true;

    sb.append("cache:");
    if (this.cache == null) {
      sb.append("null");
    } else {
      sb.append(this.cache);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("masterIP:");
    if (this.masterIP == null) {
      sb.append("null");
    } else {
      sb.append(this.masterIP);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("masterPort:");
    sb.append(this.masterPort);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LocalStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LocalStandardScheme getScheme() {
      return new LocalStandardScheme();
    }
  }

  private static class LocalStandardScheme extends org.apache.thrift.scheme.StandardScheme<Local> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Local struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CACHE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.cache = new java.util.ArrayList<cacheTable>(_list0.size);
                @org.apache.thrift.annotation.Nullable cacheTable _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new cacheTable();
                  _elem1.read(iprot);
                  struct.cache.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setCacheIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MASTER_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.masterIP = iprot.readString();
              struct.setMasterIPIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MASTER_PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.masterPort = iprot.readI32();
              struct.setMasterPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Local struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.cache != null) {
        oprot.writeFieldBegin(CACHE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.cache.size()));
          for (cacheTable _iter3 : struct.cache)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.masterIP != null) {
        oprot.writeFieldBegin(MASTER_IP_FIELD_DESC);
        oprot.writeString(struct.masterIP);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MASTER_PORT_FIELD_DESC);
      oprot.writeI32(struct.masterPort);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LocalTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LocalTupleScheme getScheme() {
      return new LocalTupleScheme();
    }
  }

  private static class LocalTupleScheme extends org.apache.thrift.scheme.TupleScheme<Local> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Local struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCache()) {
        optionals.set(0);
      }
      if (struct.isSetMasterIP()) {
        optionals.set(1);
      }
      if (struct.isSetMasterPort()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCache()) {
        {
          oprot.writeI32(struct.cache.size());
          for (cacheTable _iter4 : struct.cache)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetMasterIP()) {
        oprot.writeString(struct.masterIP);
      }
      if (struct.isSetMasterPort()) {
        oprot.writeI32(struct.masterPort);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Local struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.cache = new java.util.ArrayList<cacheTable>(_list5.size);
          @org.apache.thrift.annotation.Nullable cacheTable _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new cacheTable();
            _elem6.read(iprot);
            struct.cache.add(_elem6);
          }
        }
        struct.setCacheIsSet(true);
      }
      if (incoming.get(1)) {
        struct.masterIP = iprot.readString();
        struct.setMasterIPIsSet(true);
      }
      if (incoming.get(2)) {
        struct.masterPort = iprot.readI32();
        struct.setMasterPortIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

